# do not change the metadata.name
apiVersion: ipam.cluster.x-k8s.io/v1alpha2
kind: InClusterIPPool
metadata:
  name: clusterclass-ipv4
  annotations:
    docs: these IPs are used for the kubernetes nodes - there should be in your network range
spec:
  addresses:
  - 10.10.10.2-10.10.10.10
  gateway: 10.10.10.1
  prefix: 24