apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: proxmox-credentials
spec:
  strategy: Reconcile
  clusterSelector:
    matchLabels:
      caprox.eu/inject-proxmox-credentials: "true"
  resources:
    - name: proxmox-credentials
      kind: Secret
