apiVersion: v1
stringData:
  secret: "xxx-xxx-xxx-xxx-xxx"
  token: "xxx@pve!capi"
  # note: only the host - not the api-path
  url: "https://192.168.2.142:8006/"
kind: Secret
metadata:
  name: capmox-manager-credentials
  namespace: proxmox-infrastructure-system